# Generated by Django 3.1.2 on 2021-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aset',
            old_name='fakultas',
            new_name='aset',
        ),
        migrations.RenameField(
            model_name='aset',
            old_name='nama_dekan',
            new_name='data_created',
        ),
        migrations.RenameField(
            model_name='aset',
            old_name='user',
            new_name='name',
        ),
        migrations.AddField(
            model_name='aset',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
