# Generated by Django 3.1.2 on 2021-04-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0002_auto_20210412_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_sewa', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Databarang',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('tagihan', models.CharField(blank=True, max_length=200, null=True)),
                ('sisa_cicilan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Sewa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('agama', models.CharField(blank=True, max_length=200, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=200, null=True)),
                ('sewa', models.CharField(blank=True, choices=[('kios pasar', 'kios pasar'), ('traktor', 'traktor'), ('timbangan', 'timbangan')], max_length=200, null=True)),
                ('catatan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Penyewa',
            },
        ),
        migrations.RemoveField(
            model_name='penyewa',
            name='user',
        ),
        migrations.DeleteModel(
            name='aset',
        ),
        migrations.DeleteModel(
            name='penyewa',
        ),
    ]
