# Generated by Django 3.1.2 on 2021-04-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0003_auto_20210413_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databarang',
            name='no',
        ),
    ]
