# Generated by Django 3.1.2 on 2021-04-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0004_remove_databarang_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sewa',
            options={'verbose_name_plural': 'Sewa'},
        ),
    ]
