# Generated by Django 3.1.2 on 2021-04-13 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0005_auto_20210413_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeniskelamin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jeniskelamin',
            },
        ),
        migrations.AlterField(
            model_name='sewa',
            name='tanggal_lahir',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sewa',
            name='jenis_kelamin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sewa.jeniskelamin'),
        ),
    ]
