# Generated by Django 3.1.2 on 2021-05-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0006_auto_20210413_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='nama',
            field=models.CharField(blank=True, choices=[('kios pasar', 'kios pasar'), ('traktor', 'traktor'), ('timbangan', 'timbangan')], max_length=200, null=True),
        ),
    ]
