# Generated by Django 3.1.2 on 2021-05-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0007_auto_20210509_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='sewa',
            field=models.CharField(blank=True, choices=[('kios pasar', 'kios pasar'), ('traktor', 'traktor'), ('timbangan', 'timbangan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
