# Generated by Django 3.1.2 on 2021-05-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0011_auto_20210520_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengeluaran', models.DateTimeField(auto_now_add=True, null=True)),
                ('keterangan_pengeluaran', models.CharField(blank=True, max_length=200, null=True)),
                ('total_biaya', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pengeluaran',
            },
        ),
    ]
