# Generated by Django 3.1.2 on 2021-05-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0012_pengeluaran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengeluaran',
            options={},
        ),
    ]
