# Generated by Django 3.1.2 on 2021-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0013_auto_20210520_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengeluaran',
            options={'verbose_name_plural': 'Pengeluaran'},
        ),
        migrations.AlterField(
            model_name='pengeluaran',
            name='tanggal_pengeluaran',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
