# Generated by Django 3.1.2 on 2021-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0014_auto_20210520_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('sewa', models.CharField(blank=True, choices=[('kios pasar', 'kios pasar'), ('traktor', 'traktor'), ('timbangan', 'timbangan')], max_length=200, null=True)),
                ('tagihan', models.CharField(blank=True, max_length=200, null=True)),
                ('sisa_cicilan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Timbangan',
            },
        ),
        migrations.CreateModel(
            name='Traktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('sewa', models.CharField(blank=True, choices=[('kios pasar', 'kios pasar'), ('traktor', 'traktor'), ('timbangan', 'timbangan')], max_length=200, null=True)),
                ('tagihan', models.CharField(blank=True, max_length=200, null=True)),
                ('sisa_cicilan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Traktor',
            },
        ),
        migrations.RenameModel(
            old_name='Pembayaran',
            new_name='Kiospasar',
        ),
        migrations.AlterModelOptions(
            name='kiospasar',
            options={'verbose_name_plural': 'Kiospasar'},
        ),
    ]
