# Generated by Django 3.1.2 on 2021-05-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0015_auto_20210526_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiospasar',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
