# Generated by Django 3.1.2 on 2021-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0017_auto_20210528_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengeluaran',
            name='tanggal_pengeluaran',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
