# Generated by Django 3.1.2 on 2021-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0018_auto_20210528_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='databarang',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
