# Generated by Django 3.1.2 on 2021-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0019_databarang_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='databarang',
            name='tanggal_kembali',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databarang',
            name='tanggal_pinjaman',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
