# Generated by Django 3.1.2 on 2021-05-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0020_auto_20210529_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databarang',
            name='tanggal_kembali',
        ),
        migrations.RemoveField(
            model_name='databarang',
            name='tanggal_pinjaman',
        ),
    ]
