# Generated by Django 3.1.2 on 2021-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0021_auto_20210529_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databarang',
            old_name='profile_pic',
            new_name='gambar',
        ),
        migrations.AlterField(
            model_name='databarang',
            name='harga_sewa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
