# Generated by Django 3.1.2 on 2021-05-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0023_pembayaran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pembayaran',
            options={'verbose_name_plural': 'Pembayaran'},
        ),
    ]
