# Generated by Django 3.1.2 on 2021-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0024_auto_20210529_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angsuran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('sewa', models.CharField(blank=True, choices=[('kios pasar', 'kios pasar')], max_length=200, null=True)),
                ('tagihan', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('bayar', 'bayar'), ('belum bayar', 'belum bayar')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Angsuran',
            },
        ),
    ]
