# Generated by Django 3.1.2 on 2021-05-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0025_angsuran'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kiospasar',
        ),
        migrations.DeleteModel(
            name='Timbangan',
        ),
        migrations.DeleteModel(
            name='Traktor',
        ),
    ]
