# Generated by Django 3.1.2 on 2021-05-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0026_auto_20210529_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Penyewa',
        ),
    ]
