# Generated by Django 3.1.2 on 2021-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0028_auto_20210530_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databarang',
            name='gambar',
            field=models.ImageField(blank=True, default='fotokosong.gif', upload_to=''),
        ),
    ]
