# Generated by Django 3.1.2 on 2021-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0029_auto_20210530_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sewa',
            old_name='nama',
            new_name='nama_lengkap',
        ),
        migrations.AddField(
            model_name='sewa',
            name='tanggal_kembali',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sewa',
            name='tanggal_pinjam',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
