# Generated by Django 3.1.2 on 2021-05-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0030_auto_20210530_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewa',
            name='agama',
        ),
        migrations.RemoveField(
            model_name='sewa',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='sewa',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='sewa',
            name='tanggal_lahir',
        ),
        migrations.RemoveField(
            model_name='sewa',
            name='tempat_lahir',
        ),
    ]
