# Generated by Django 3.1.2 on 2021-06-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0034_auto_20210601_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
