# Generated by Django 3.1.2 on 2021-06-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0037_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penyewa',
        ),
    ]
