# Generated by Django 3.1.2 on 2021-06-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0038_delete_penyewa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
