# Generated by Django 3.1.2 on 2021-06-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0039_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Databarang',
        ),
    ]
