# Generated by Django 3.1.2 on 2021-06-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0047_auto_20210607_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status',
            field=models.CharField(choices=[('kios pasar', 'kios pasar'), ('traktor', 'traktor'), ('timbangan', 'timbangan')], max_length=200, null=True),
        ),
    ]
