# Generated by Django 3.1.2 on 2021-06-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0048_auto_20210607_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status',
            field=models.CharField(choices=[('bayar', 'bayar'), ('belum bayar', 'belum bayar')], max_length=200, null=True),
        ),
    ]
