# Generated by Django 3.1.2 on 2021-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0049_auto_20210607_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='tag',
            field=models.ManyToManyField(to='sewa.Tag'),
        ),
    ]
