# Generated by Django 3.1.2 on 2021-06-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0053_remove_pembayaran_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sewa',
        ),
    ]
