# Generated by Django 3.1.2 on 2021-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0055_auto_20210607_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
    ]
