# Generated by Django 3.1.2 on 2021-06-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0058_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
    ]
