# Generated by Django 3.1.2 on 2021-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0062_auto_20210609_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='fotokosong.gif', upload_to='static/images'),
        ),
    ]
