# Generated by Django 3.1.2 on 2021-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0066_auto_20210611_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='alamat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nik',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telepon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
