# Generated by Django 3.1.2 on 2021-06-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0072_orderitem_nik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='nik',
        ),
    ]
