# Generated by Django 3.1.2 on 2021-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0073_remove_orderitem_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('bayar', 'bayar'), ('belum bayar', 'belum bayar')], max_length=200, null=True),
        ),
    ]
