# Generated by Django 3.1.2 on 2021-06-12 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sewa', '0075_auto_20210612_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Barang',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Penyewa',
        ),
        migrations.DeleteModel(
            name='Jeniskelamin',
        ),
        migrations.DeleteModel(
            name='Pembayaran',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='penyewa',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='barang',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='penyewa',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='penyewa',
        ),
    ]
