# Generated by Django 3.1.2 on 2021-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0076_auto_20210612_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='stok',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
