# Generated by Django 3.1.2 on 2021-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0077_barang_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='nik',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
