# Generated by Django 3.1.2 on 2021-06-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0079_remove_orderitem_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
