# Generated by Django 3.1.2 on 2021-06-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0080_auto_20210612_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='barang',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_orderd',
            new_name='tanggal_pesan',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='jumlah',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='tanggal_pesan',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
