# Generated by Django 3.1.2 on 2021-06-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0086_auto_20210613_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('digital', models.BooleanField(default=False, null=True)),
                ('stok', models.IntegerField(default=False, null=True)),
                ('image', models.ImageField(blank=True, default='fotokosong.gif', upload_to='static/images')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('bayar', 'bayar')], default='belum_bayar', max_length=200),
        ),
    ]
