# Generated by Django 3.1.2 on 2021-06-16 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sewa', '0087_auto_20210613_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'DetailTransaksi',
            },
        ),
        migrations.CreateModel(
            name='TempBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'TempBarang',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('total_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.DeleteModel(
            name='Barang1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='penyewa',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='nama',
        ),
        migrations.AddField(
            model_name='barang',
            name='barang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='stok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='tempbarang',
            name='barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sewa.barang'),
        ),
        migrations.AddField(
            model_name='tempbarang',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sewa.barang'),
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
