# Generated by Django 3.1.2 on 2021-06-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0088_auto_20210616_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name_plural': 'Barang'},
        ),
        migrations.RemoveField(
            model_name='tempbarang',
            name='user',
        ),
        migrations.AddField(
            model_name='tempbarang',
            name='penyewa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sewa.penyewa'),
        ),
    ]
