# Generated by Django 3.1.2 on 2021-06-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0089_auto_20210617_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='user',
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='penyewa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sewa.penyewa'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='penyewa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sewa.penyewa'),
        ),
    ]
