# Generated by Django 3.1.2 on 2021-06-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0090_auto_20210617_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sewa.barang'),
        ),
    ]
