# Generated by Django 3.1.2 on 2021-06-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0091_transaksi_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='barang',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('bayar', 'bayar'), ('belumbayar', 'belumbayar')], max_length=200, null=True),
        ),
    ]
