# Generated by Django 3.1.2 on 2021-06-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0092_auto_20210617_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='status',
        ),
        migrations.AddField(
            model_name='barang',
            name='status',
            field=models.CharField(choices=[('sewa', 'Sewa'), ('angsuran', 'Angsuran')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='keterangan',
            field=models.CharField(choices=[('bayar', 'bayar'), ('belumbayar', 'belumbayar')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='status',
            field=models.CharField(choices=[('sewa', 'Sewa'), ('angsuran', 'Angsuran')], max_length=200, null=True),
        ),
    ]
