# Generated by Django 3.1.2 on 2021-06-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0093_auto_20210618_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penyewa',
            options={'verbose_name_plural': 'Penyewa'},
        ),
        migrations.AddField(
            model_name='tempbarang',
            name='status',
            field=models.CharField(choices=[('sewa', 'Sewa'), ('angsuran', 'Angsuran')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='no_transaksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='no_transaksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
