# Generated by Django 3.1.7 on 2021-06-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0095_auto_20210617_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtransaksi',
            name='jml_pinjam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempbarang',
            name='jml_pinjam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
