# Generated by Django 3.1.7 on 2021-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0096_auto_20210617_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbarang',
            name='tanggal_kembali',
            field=models.DateField(null=True),
        ),
    ]
