# Generated by Django 3.1.2 on 2021-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0101_pengeluaran_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='image',
            field=models.ImageField(blank=True, default='fotokosong.gif', upload_to='static/images/static/'),
        ),
    ]
