# Generated by Django 3.1.2 on 2021-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0102_auto_20210620_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempbarang',
            name='tanggal_kembali',
            field=models.DateField(choices=[('harian', 'harian'), ('tahunan', 'tahunan')], null=True),
        ),
    ]
