# Generated by Django 3.1.2 on 2021-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0103_auto_20210620_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempbarang',
            name='tanggal_kembali',
            field=models.DateField(choices=[('kembali', 'kembali')], null=True),
        ),
    ]
