# Generated by Django 3.1.2 on 2021-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0104_auto_20210620_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='date_created',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='keterangan',
            field=models.CharField(choices=[('bayar', 'bayar'), ('belum_bayar', 'belum_bayar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='tanggal_kembali',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempbarang',
            name='tanggal_kembali',
            field=models.DateField(null=True),
        ),
    ]
