# Generated by Django 3.1.2 on 2021-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0105_auto_20210620_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksi',
            name='tanggal_kembali',
            field=models.CharField(blank=True, choices=[('kembali', 'kembali'), ('belumkembali', 'belumkembali')], max_length=200, null=True),
        ),
    ]
