# Generated by Django 3.1.2 on 2021-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0109_tempbarang_pengembalian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempbarang',
            name='pengembalian',
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='pengembalian',
            field=models.CharField(blank=True, choices=[('kembali', 'kembali'), ('belum_kembali', 'belum_kembali')], max_length=200, null=True),
        ),
    ]
