# Generated by Django 3.1.2 on 2021-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0111_auto_20210803_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='keterangan',
            field=models.CharField(choices=[('Bayar', 'Bayar'), ('Belum Bayar', 'Belum Bayar')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='pengembalian',
            field=models.CharField(blank=True, choices=[('Kembali', 'Kembali'), ('Belum Kembali', 'Belum Kembali')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('Harian', 'Harian'), ('Tahunan', 'Tahunan')], max_length=200, null=True),
        ),
    ]
