# Generated by Django 3.1.2 on 2021-08-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0113_auto_20210803_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='pengembalian',
        ),
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='status',
        ),
    ]
