# Generated by Django 3.1.2 on 2021-08-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0114_auto_20210803_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='barang',
        ),
    ]
