# Generated by Django 3.1.2 on 2021-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0117_auto_20210803_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtransaksi',
            name='total_transaksi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
