# Generated by Django 3.1.2 on 2021-08-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0118_detailtransaksi_total_transaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='total_transaksi',
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='transaksi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sewa.transaksi'),
        ),
    ]
