# Generated by Django 3.1.2 on 2021-08-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0121_auto_20210803_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailtransaksi',
            old_name='transaksi',
            new_name='total_transaksi',
        ),
    ]
