# Generated by Django 3.1.2 on 2021-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0123_auto_20210803_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='transaksi',
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='total_transaksi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
