# Generated by Django 3.1.2 on 2021-08-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0124_auto_20210803_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempbarang',
            name='total_transaksi',
        ),
    ]
