# Generated by Django 3.1.2 on 2021-08-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0126_remove_detailtransaksi_total_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtransaksi',
            name='total_transaksi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
